// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZX6ijIzHYHJUl3wvcL1CGk8kj3YM-gmg',
    appId: '1:358631747068:web:564b7865e227e27c619679',
    messagingSenderId: '358631747068',
    projectId: 'food-delivery-app-9f528',
    authDomain: 'food-delivery-app-9f528.firebaseapp.com',
    storageBucket: 'food-delivery-app-9f528.appspot.com',
    measurementId: 'G-QT9V71G780',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtRE-v0y7Ou3-G96HA-8MUnmGW0nJESws',
    appId: '1:358631747068:android:e728f4bf5a9694a2619679',
    messagingSenderId: '358631747068',
    projectId: 'food-delivery-app-9f528',
    storageBucket: 'food-delivery-app-9f528.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG0eEDMq-P3AVW6kxRM9UfnA1GcSM1m0A',
    appId: '1:358631747068:ios:92423ee708fdbdac619679',
    messagingSenderId: '358631747068',
    projectId: 'food-delivery-app-9f528',
    storageBucket: 'food-delivery-app-9f528.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG0eEDMq-P3AVW6kxRM9UfnA1GcSM1m0A',
    appId: '1:358631747068:ios:92423ee708fdbdac619679',
    messagingSenderId: '358631747068',
    projectId: 'food-delivery-app-9f528',
    storageBucket: 'food-delivery-app-9f528.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZX6ijIzHYHJUl3wvcL1CGk8kj3YM-gmg',
    appId: '1:358631747068:web:c71ff19f73368d3b619679',
    messagingSenderId: '358631747068',
    projectId: 'food-delivery-app-9f528',
    authDomain: 'food-delivery-app-9f528.firebaseapp.com',
    storageBucket: 'food-delivery-app-9f528.appspot.com',
    measurementId: 'G-GM073XR7J2',
  );
}
